pipeline {

    agent any

    stages {

        stage('build'){

            steps{
                slackSend color: "#99ff66", message: "start build"
               
            }
        }


        stage('docker'){

            steps{
                slackSend color: "#66ff99", message: "start build docker"
                 sh "sudo docker build . -t shafey/jenkins-nginx"
            }
        }

        stage('docker push'){

            environment {
                
                DOCKERHUB_USERNAME = credentials('dockerhub_USERNAME')
                DOCKERHUB_PASSWORD = credentials('dockerhub_PASSWORD')
                
           }

            steps{
                slackSend color: "#66ff99", message: "start build docker push"
                 sh "sudo docker login -u  $DOCKERHUB_USERNAME  -p $DOCKERHUB_PASSWORD"
                 sh "sudo docker push shafey/jenkins-nginx"
            }
        }

        stage('docker pull'){

            steps{
                slackSend color: "#66ff99", message: "start docker pull"
                 sh "sudo docker pull shafey/jenkins-nginx"
            }
        }
        
        stage('docker test on localhost'){

            steps{
                slackSend color: "#66ff99", message: "start run docker on localhost"
                 sh "sudo docker rm -f $(docker ps -qa)"
                 sh "sudo docker run -d -p 82:80 shafey/jenkins-nginx"
            }
        }

    }
    post { 
            success { 
                slackSend color: "good", message: "pipeline succesed"

            }

            


        }

}


