pipeline {

    agent any

    stages {

        stage('build'){

            steps{
                slackSend color: "#99ff66", message: "start build"
               
            }
        }


        stage('docker'){

            steps{
                slackSend color: "#66ff99", message: "start build docker"
                 sh "sudo docker build . -t shafey/jenkins-nginx"
            }
        }

        stage('docker push'){

            steps{
                slackSend color: "#66ff99", message: "start build docker push"
                 sh "sudo docker login -u ${{ dockerhub.Username }} -p ${{ dockerhub.Password }} . -t shafey/jenkins-nginx"
                 sh "sudo docker push shafey/jenkins-nginx"
            }
        }
        

    }
    post { 
            success { 
                slackSend color: "good", message: "pipeline succesed"

            }

            


        }

}


